import numpy

def freestream_get_stream_function(U, alpha, X, Y):
    """Returns the stream-function generated by a source/sink.
    
    Arguments
    ---------
    U -- freestream speed.
    alpha -- angle of attack
    X, Y -- mesh grid.
    """
    psi = U*(Y*numpy.cos(alpha) - X*numpy.sin(alpha))
    
    return psi
    
def freestream_get_velocity(U, alpha, X, Y):
    """Returns the velocity field generated by a source/sink.
    
    Arguments
    ---------
    U -- freestream speed.
    alpha -- angle of attack
    X, Y -- mesh grid.
    """
    u = U*numpy.cos(alpha)
    v = U*numpy.sin(alpha)
    
    return u, 0

def source_get_stream_function(strength, xs, ys, X, Y):
    """Returns the stream-function generated by a source/sink.
    
    Arguments
    ---------
    strength -- strength of the source/sink.
    xs, ys -- coordinates of the source/sink.
    X, Y -- mesh grid.
    """
    psi = strength/(2*numpy.pi)*numpy.arctan2((Y-ys), (X-xs))
    
    return psi
    
    
def source_get_velocity(strength, xs, ys, X, Y):
    """Returns the velocity field generated by a source/sink.
    
    Arguments
    ---------
    strength -- strength of the source/sink.
    xs, ys -- coordinates of the source/sink.
    X, Y -- mesh grid.
    """
    u = strength/(2*numpy.pi)*(X-xs)/((X-xs)**2+(Y-ys)**2)
    v = strength/(2*numpy.pi)*(Y-ys)/((X-xs)**2+(Y-ys)**2)
    
    return u, v
