import math, numpy

def freestream_get_stream_function(U, alpha, X, Y):
    """Returns the stream-function generated by a source/sink.
    
    Arguments
    ---------
    U -- freestream speed.
    alpha -- angle of attack
    X, Y -- mesh grid.
    """
    psi = U*(Y*math.cos(alpha) - X*math.sin(alpha))
    
    return psi
    
def freestream_get_velocity(U, alpha, X, Y):
    """Returns the velocity field generated by a source/sink.
    
    Arguments
    ---------
    U -- freestream speed.
    alpha -- angle of attack
    X, Y -- mesh grid.
    """
    u = U*math.cos(alpha) * numpy.ones_like(X)
    v = U*math.sin(alpha) * numpy.ones_like(X)
    
    return u, v

def source_get_stream_function(strength, xs, ys, X, Y):
    """Returns the stream-function generated by a source/sink.
    
    Arguments
    ---------
    strength -- strength of the source/sink.
    xs, ys -- coordinates of the source/sink.
    X, Y -- mesh grid.
    """
    psi = strength/(2*math.pi)*numpy.arctan2((Y-ys), (X-xs))
    
    return psi
    
def source_get_velocity(strength, xs, ys, X, Y):
    """Returns the velocity field generated by a source/sink.
    
    Arguments
    ---------
    strength -- strength of the source/sink.
    xs, ys -- coordinates of the source/sink.
    X, Y -- mesh grid.
    """
    u = strength/(2*math.pi)*(X-xs)/((X-xs)**2+(Y-ys)**2)
    v = strength/(2*math.pi)*(Y-ys)/((X-xs)**2+(Y-ys)**2)
    
    return u, v

def doublet_get_stream_function(strength, xd, yd, X, Y):
    """Returns the stream-function generated by a doublet.
    
    Arguments
    ---------
    strength -- strength of the doublet.
    xd, yd -- coordinates of the doublet.
    X, Y -- mesh grid.
    """
    psi = - strength/(2*math.pi)*(Y-yd)/((X-xd)**2+(Y-yd)**2)
    
    return psi
    
def doublet_get_velocity(strength, xd, yd, X, Y):
    """Returns the velocity field generated by a doublet.
    
    Arguments
    ---------
    strength -- strength of the doublet.
    xd, yd -- coordinates of the doublet.
    X, Y -- mesh grid.
    """
    u = - strength/(2*math.pi)*((X-xd)**2-(Y-yd)**2)/((X-xd)**2+(Y-yd)**2)**2
    v = - strength/(2*math.pi)*2*(X-xd)*(Y-yd)/((X-xd)**2+(Y-yd)**2)**2
    
    return u, v